### PR TITLE
WhatWeOfferSection

### PR DESCRIPTION
**Pull request by SrilakshmiSripathi**
### Summary

WhatWeOffer section of the VisiUI

### Details
- Completed One source truth for information `Homepage.json`. 
- Added WhatWeOffer section

### Things to do:
- Making responsive
- Optimizing Grid Layout to make it reusable

### References
[
GridLayout
](url)

### Checks

- [x] No errors
- [x] No Bugs
- [x] Ran the command `npm run build`
- [x] Ran the command `npm run lint`
- [x] Ran the command `npm run dev`
- [ ] Ran the command `npx prettier . --write`

### CODE REVIEW

**Comment by angeldevildev** [comment]
I'll check when I'm home

**Comment by angeldevildev** [comment]
image
@SrilakshmiSripathi That's how it would look like in the Vercel deployment

**Comment by angeldevildev** [comment]
image
This is how it would look like in the Vercel Deployment, you should add some padding in the top of the "What We Offer Text" and some distance from the header and from the Why Choose Us section. 
And the background does not have to be the whole screen but just enough to contain the lettering

@SrilakshmiSripathi

**Comment by angeldevildev** [comment]
image
Here's the error to resolve

**Comment by angeldevildev** [comment]
Add some gap beetween the What We Offer and the Why Choose Us text

**Comment by theonewhoknocks878** [comment]
@SrilakshmiSripathi The work you've done looks great!

**Review by theonewhoknocks878 — APPROVED** [review]
Cool!

**Review by angeldevildev — COMMENTED** [review]
Ok

**Pull request merged**
